* 内容提要
* 第1章 Ubuntu安装与基本使用
● 用户应用程序：位于整个系统的最顶层，是Linux系统上运行的应用程序集合，常见的用户应用程序有字处理应用程序、多媒体处理应用程序、网络应用程序等。● 操作系统服务：位于用户应用程序与系统内核之间，主要是指那些为用户提供服务且执行操作系统部分功能的程序，为应用程序提供系统内核的调用接口。X窗口系统、Shell命令解释系统、内核编程接口等就属于操作系统服务子系统。这一部分也称为系统程序。● Linux内核：靠近硬件的是内核，即Linux操作系统常驻内存部分。Linux内核是整个操作系统的核心，由它实现对硬件资源的抽象和访问调度。它为上层调用提供了一个统一的虚拟机器接口，在编写上层程序的时候不需要考虑计算机使用何种类型的物理硬件，也不需要考虑临界资源问题。每个上层进程执行时就像它是计算机上的唯一进程，独占了系统的所有内存和其他硬件资源。但实际上，系统可以同时运行多个进程，由Linux内核保证各进程对临界资源的安全使用。所有运行在内核之上的程序可分为系统程序和用户程序两大类，但它们统统运行在用户模式之下。内核之外的所有程序必须通过系统调用才能进入操作系统的内核。● 硬件系统：包含Linux所使用的所有物理设备，如CPU、内存、硬盘和网络设备等。

用户在登录到Linux字符界面时，可以在提示信息中看到内核版本号。也可以随时执行命令uname-r来查看系统的内核版本号。

Linux使用设备名称加分区编号来标明分区。SCSI磁盘、SATA磁盘（串口硬盘）均可表示为“sd”，并且在“sd”之后使用小写字母表示磁盘编号，磁盘编号之后是分区编号，使用阿拉伯数字表示（主分区或扩展分区的分区编号为1～4，逻辑分区的分区编号从5开始）。例如，第一块SCSI或SATA磁盘被命名为sda，第二块为sdb，第一块磁盘的第一个主分区表示为sda1，第二个主分区表示为sda2。IDE磁盘使用“hd”表示，表示方法同SCSI磁盘。

直接在Linux计算机上的登录称为从控制台登录，使用telnet、SSH等工具通过网络登录到Linux主机称为远程登录。在文本模式下从控制台登录的界面又称终端（TTY）。
在Ubuntu图形界面中可按组合键<Ctrl>+<Alt>+<F(n)>（其中F(n)为F1～F6，分别代表1~6号控制台）切换到文本控制台界面，在文本控制台界面中按组合键<Ctrl>+<Alt>+<F7>返回到图形界面。例如，按组合键<Ctrl>+<Alt>+<F1>进入1号控制台，分别输入用户名和口令（密码），就可以登录到Linux系统，如图2-8所示。

● 解释用户在命令行提示符下输入的命令。这是最主要的功能。● 提供个性化的用户环境，通常由Shell初始化配置文件（如.profile、.login等）实现。● 编写Shell脚本，实现高级管理功能。


正则表达式（Regular Expression，RE）是一种可以用于模式匹配和替换的工具。通过正则表达式，Shell可以使用一系列的特殊字符构建匹配模式，然后将匹配模式与待比较字符串或文件进行比较，根据比较对象中是否包含匹配模式，执行相应的程序。

每个用户登录系统后，都会有一个专用的运行环境。通常各个用户默认的环境都是相同的，这个默认环境实际上就是一组环境变量的定义。用户可直接引用环境变量，也可修改环境变量来定制运行环境。常用的环境变量有PATH（可执行命令的搜索路径）、HOME（用户主目录）、LOGNAME（当前用户的登录名）、HOSTNAME（主机名）、PS1（当前命令提示符）、SHELL（用户当前使用的Shell）等。

使用env命令可显示所有的环境变量。

#+BEGIN_SRC bash
wc < 文件名
#+END_SRC
#+BEGIN_SRC bash
ls >>文件名
#+END_SRC
管道用于将一个命令的输出作为另一个命令的输入，使用符号“|”来连接命令。可以将多个命令依次连接起来，前一个命令的输出作为后一个命令的输入。基本用法：
#+BEGIN_SRC bas
命令1 | 命令2 …… | 命令n
ls | grep "ab"
cat /etc/log/messages | more
#+END_SRC
(1)用户账户配置文件/etc/passdw
账户名:密码:UID:GID:注释:主目录:Shell
各字段说明如下。
● 账户名是用户名，又称登录名。最长不超过32个字符，可使用下画线和连字符。
● 密码使用x表示，因为passwd文件不保存密码信息。
● UID是用户账户的编号。
● GID用于标识用户所属的默认组。
● 注释可以是用户全名或其他说明信息（如电话）。
● 主目录是用户登录后首次进入的目录，这里必须使用绝对路径。
● Shell是用户登录后所使用的一个命令行界面。
Ubuntu安装过程中创建的第一个用户账户作为管理员，除了属于以它自己命名的主要组外，还属于adm、cdrom、sudo、dip、plugdev、lpadmin、sambashare等系统组。

#+BEGIN_SRC bash
cat /etc/passwd | grep zhang 　　
awk -F':' '{ print $1}' /etc/passwd
#+END_SRC
* 文件与目录管理
** Linux文件与目录概述
文件是Linux操作系统处理信息的基本单位，所有软件都以文件形式进行组织。目录是包含许多文件项目的一类特殊文件，每个文件都登记在一个或多个目录中。
*** 4.1.2 Linux目录配置标准——FHS
● /bin：存放用于系统管理维护的常用实用命令文件。● /boot：存放用于系统启动的内核文件和引导装载程序文件。● /dev：存放设备文件。● /etc：存放系统配置文件，如网络配置、设备配置、X Window系统配置等。● /home：各个用户的主目录，其中的子目录名称即为各用户名。● /lib：存放动态连接共享库（其作用类似于Windows里的.dll文件）。● /media：为光盘、软盘等设备提供的默认挂载点。● /mnt：为某些设备提供的默认挂载点。● /root：root用户主目录。不要将其与根目录混淆。● /proc：系统自动产生的映射。查看该目录中的文件可获取有关系统硬件运行的信息。● /sbin：存放系统管理员或者root用户使用的命令文件。● /usr：存放应用程序和文件。● /var：保存经常变化的内容，如系统日志、打印。


使用ls-l命令以长格式列目录时，每一行第1个字符代表文件类型。其中-表示普通文件，d表示目录文件，c表示字符设备文件，b表示块设备文件，l表示符号链接文件。

ls -R 递归的显示目录

2. 文件内容比较
comm命令对两个已经排好序的文件进行逐行比较，只显示它们共有的行。语法格式如下：
diff命令

6. 文件查找
   （1）find命令
该命令用于在目录结构中搜索满足查询条件的文件并执行指定操作。语法格式如下：　　find [路径…] [匹配表达式]
#+BEGIN_SRC bash
sudo find /etc -name "passwd*" -exec grep "wang" {} \;
#+END_SRC
（2）locate命令
** 4.4 管理文件和目录权限
所有者（owner）、所属组（group）和其他用户（others），
读（read）、写（write）和执行（execute）
#+BEGIN_SRC bash
　chmod g+w,o+r /home/wang/myfile // 给所属组用户增加写权限，给其他用户增加读权限 　　chmod go-r /home/wang/myfile // 同时撤销所属组和其他用户对该文件的读权限　　chmod a=rx /home/wang/myfile // 对所有用户赋予读和执行权限
#+END_SRC
#+BEGIN_SRC bash
chmod 644 file
#+END_SRC
* 磁盘存储管理
** 5.1 Linux磁盘存储概述
   磁盘用来存储需要永久保存的数据，常见的磁盘包括硬盘、光盘、闪存（Flash Memory，如U盘、CF存储卡、SD存储卡）等。这里的磁盘主要是指硬盘。磁盘在系统中使用都必须先进行分区，然后对分区格式化，这样才能用来保存文件和数据。
命令行工具可以使用fdisk和parted。fdisk是各种Linux发行版本中最常用的分区工具，使用灵活，简单易用。parted功能更强大，支持的分区类型非常多，而且可以调整原有分区尺寸，只是操作复杂一些。
5.5.3 使用dump和restore实现备份和恢复dump是一个较为专业的备份工具，能备份任何类型的文件，甚至是设备，支持完全备份、增量备份和差异备份，支持跨多卷磁带备份，保留所备份文件的所有权属性和权限设置，能够正确处理从未包含任何数据的文件块（空洞文件）。restore是对应的恢复工具。
* 第6章 软件包管理
Linux虽然没有Windows那样的注册表，但是要考虑软件的依赖性问题。
所谓软件包，是指将应用程序、配置文件以及数据等支持文件打包成一个文件。f
1. Ubuntu软件中心
   2. APT工具
      3. PPA安装
APT和Ubuntu软件中心都是软件源安装方式，通常从Ubuntu官方仓库中获取软件。考虑到稳定性，Ubuntu官方仓库收录的软件比较正式，版本相对滞后。对于一些没有收录到Ubuntu官方仓库的软件，可以通过PPA这种非正式的软件仓库提供。
Ubuntu的/var/lib/apt/lists目录存放的是已经下载的各软件源的元数据（metadata），这些数据是系统更新和软件包查找工具的基础。Ubuntu软件中心、APT（包括新立得软件包管理器）和软件更新器（Update Manager）等工具就是利用这些信息来更新和安装软件的。Ubuntu软件中心和APT安装和卸载软件的信息来源是/var/lib/dpkg/states，查询软件的信息来源是/var/lib/apt/lists。软件更新器将系统已经安装的软件版本信息（存放在/var/lib/dpkg/states目录）与/var/lib/apt/lists/目录中同名的软件版本进行比较，以判断是否更新，然后将所有需要更新的软件在窗口中列出。
** 6.2 APT工具
 常用的APT命令行工具有两个，apt-get用于执行与软件包安装有关的所有操作，apt-cache用于查询软件包的相关信息。
1. 使用apt-cache命令查询软件包
   #+BEGIN_SRC bash
   　apt-cache pkgnames
   apt-cache search httpd
   　apt-cache show 软件包名
   　apt-cache depends 软件包名
   apt-cache rdepends 软件包名
   apt-cache showpkg 软件包名
   　apt-cache policy 软件包名
   #+END_SRC
如果要同时删除配置文件，则要执行apt-get purge命令。

新立得软件包
#+BEGIN_SRC bash
　apt-get install synaptic
#+END_SRC
*** PPA安装
APT和Ubuntu软件中心都可以添加PPA安装源。所有的PPA都寄存在launchpad.net网站上，供Ubuntu用户使用。
** 6.3 安装软件包文件
注意Ubuntu的软件包格式是.deb，不应当直接安装RPM包。如果要安装RPM包，则要先用alien工具将.rpm转换成.deb格式。默认没有安装alien，可以执行以下命令安装它。
** 6.4 使用源代码安装
   tar-jxvf file.tar.bz2 　　tar-zxvf file.tar.gz
   项-j指示具有bzip2的属性，即需要用bzip2格式压缩或解压缩。选项-z指示具有gzip的属性，即需要用gzip格式压缩或解压缩。选项-x用于解开一个压缩文件。选项-v表示在压缩过程中显示文件。
   源代码包安装的3个步骤configure、make和make install依次执行，其中只要一个步骤无法成功，后续的步骤就无法进行。另外，执行make install安装的软件通常可以执行make clean命令卸载。
* Linux进程管理
ps
其中，USER表示进程的所有者，PID是进程号，%CPU表示占用CPU的百分比，%MEM表示占用内存的百分比，VSZ表示占用虚拟内存的数量，RSS表示驻留内存的数量，TTY表示进程的控制终端（值“?”说明该进程与控制终端没有关联），STAT表示进程的运行状态（R代表准备就绪状态，S是可中断的休眠状态，D是不可中断的休眠状态，T是暂停执行，Z表示不存在但暂时无法消除，W表示无足够内存页面可分配，<表示高优先级，N表示低优先级，L表示内存页面被锁定，s表示创建会话的进程，1表示多线程进程，+表示是一个前台进程组），START是进程开始的时间，TIME是进程已经执行的时间，COMMAND是进程对应的程序名称和运行参数。
#+BEGIN_SRC bash
ps aux | less

#+END_SRC

#+BEGIN_SRC bash
ps -e | grep xinetd
#+END_SRC


命令nice可用于设置进程的优先级，用法如下：　
#+BEGIN_SRC bash
　nice [-n] [命令 [参数] ... ]
#+END_SRC
n表示优先级值，默认值为10；命令表示进程名，参数是该命令所带的参数。
（1）BIOS启动
（2）启动引导加载程序
（3）装载内核
GRUB全称GRand Unified Bootloader，作为一种多重操作系统启动管理器，除引导Linux之外，也可在多操作系统共存时管理多重操作系统的引导。管理员可对GRUB进行配置管理来干预系统的启动。

在Linux系统中有些程序在启动之后持续在后台运行，等待用户或其他应用程序调用，此类程序就是服务（service）。大多数服务都是通过守护进程（daemon）实现的。守护进程一旦开启，就在后台运行并时刻监视着系统前台，一旦前台发出指令或请求，守护进程立即做出响应以提供相应的服务。
